[profile.default]
fs_permissions = [{ access = "read-write", path = "./deployments/arc-testnet" }]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"
remappings = ["v4-core/=lib/v4-core/"]

[fmt]
ignore = ["lib/**"]

[invariant]
runs = 256
depth = 500
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
